- id: alert_hot_tub_temperature_low
  alias: 'Alert: Hot Tub Temperature Low'
  trigger:
    - platform: numeric_state
      entity_id: sensor.hottub_temperature
      below: 38
      for:
        minutes: 5
  action:
    - service: notify.armoury_pushover
      data:
        message: Hot tub has been below temperature for 5 minutes.
        title: 'The Armoury: Hot Tub'
        data:
          priority: 1
- id: alert_rain_detected
  alias: 'Alert: Rain Detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.opensprinkler_rain_sensor
      from: 'off'
      to: 'on'
  action:
    - service: notify.armoury_pushover
      data:
        message: Sprinklers have been disabled because rain was detected.
        title: 'The Armoury: Rain Detected'
        data:
          priority: 0
- id: alert_rain_not_detected
  alias: 'Alert: Rain Not Detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.opensprinkler_rain_sensor
      from: 'on'
      to: 'off'
  action:
    - service: notify.armoury_pushover
      data:
        message: Sprinklers have been enabled after rain detection has dried up.
        title: 'The Armoury: Rain Detection Timed Out'
        data:
          priority: 0
- id: alert_garage_door_closed
  alias: 'Alert: Garage Door Closed'
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_main_door
      from: 'on'
      to: 'off'
  action:
    - service: notify.armoury_pushover
      data:
        message: Garage door was closed.
        title: 'The Armoury: Garage'
        data:
          priority: 0
- id: alert_garage_door_opened
  alias: 'Alert: Garage Door Opened'
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_main_door
      from: 'off'
      to: 'on'
  action:
    - service: notify.armoury_pushover
      data:
        message: Garage door was opened.
        title: 'The Armoury: Garage'
        data:
          priority: 0
- id: alert_front_door_unlocked
  alias: 'Alert: Front Door Unlocked'
  trigger:
    - platform: state
      entity_id: lock.assa_abloy_yale_push_button_deadbolt_yrd210_locked
      from: locked
      to: unlocked
  action:
    - service: notify.armoury_pushover
      data:
        message: Front door was unlocked.
        title: 'The Armoury: House'
        data:
          priority: -1
- id: alert_side_door_unlocked
  alias: 'Alert: Side Door Unlocked'
  trigger:
    - platform: state
      entity_id: lock.assa_abloy_yale_push_button_deadbolt_yrd210_locked_2
      from: locked
      to: unlocked
  action:
    - service: notify.armoury_pushover
      data:
        message: Side door was unlocked.
        title: 'The Armoury: House'
        data:
          priority: -1
- id: alert_front_door_opened
  alias: 'Alert: Front Door Opened'
  trigger:
    - platform: state
      entity_id: binary_sensor.aeotec_zw112_door_window_sensor_6_sensor_2
      from: 'off'
      to: 'on'
  action:
    - service: notify.armoury_pushover
      data:
        message: Front door was opened.
        title: 'The Armoury: House'
        data:
          priority: 0
- id: alert_side_door_opened
  alias: 'Alert: Side Door Opened'
  trigger:
    - platform: state
      entity_id: binary_sensor.aeotec_zw112_door_window_sensor_6_sensor
      from: 'off'
      to: 'on'
  action:
    - service: notify.armoury_pushover
      data:
        message: Side door was opened.
        title: 'The Armoury: House'
        data:
          priority: 0
- id: alert_master_bedroom_high_heat
  alias: 'Alert: High Heat In Master Bedroom'
  trigger:
    - platform: numeric_state
      entity_id: sensor.FIBARO_System_FGMS001ZW5_Motion_Sensor_Temperature
      above: 26.5
  action:
    - service: notify.armoury_pushover
      data:
        message: Master bedroom has high heat!
        title: 'The Armoury: House'
        data:
          priority: 1
    - service: switch.turn_off
      data:
        entity_id: switch.Aeotec_ZW096_Smart_Switch_6_Switch
- id: alert_master_bedroom_fireplace_turned_on
  alias: 'Alert: Master Bedroom Fireplace Turned On'
  trigger:
    - platform: state
      entity_id: switch.Aeotec_ZW096_Smart_Switch_6_Switch
      from: 'off'
      to: 'on'
  action:
    - service: notify.armoury_pushover
      data:
        message: Master bedroom fireplace turned on.
        title: 'The Armoury: House'
        data:
          priority: -2
- id: alert_master_bedroom_fireplace_turned_off
  alias: 'Alert: Master Bedroom Fireplace Turned Off'
  trigger:
    - platform: state
      entity_id: switch.Aeotec_ZW096_Smart_Switch_6_Switch
      from: 'on'
      to: 'off'
  action:
    - service: notify.armoury_pushover
      data:
        message: Master bedroom fireplace turned off.
        title: 'The Armoury: House'
        data:
          priority: -2
- id: alert_home_temperature_too_low
  alias: 'Alert: Home Temperature Too Low'
  trigger:
    - platform: numeric_state
      entity_id: sensor.ELINA_Thermostat_temperature
      below: 16
  action:
    - service: notify.armoury_pushover
      data:
        message: Home temperature dropped below 16 degrees celcius.
        title: 'The Armoury: House'
        data:
          priority: 0
- id: alert_home_temperature_too_high
  alias: 'Alert: Home Temperature Too High'
  trigger:
    - platform: numeric_state
      entity_id: sensor.ELINA_Thermostat_temperature
      above: 24
  action:
    - service: notify.armoury_pushover
      data:
        message: Home temperature is above 24 degrees celcius.
        title: 'The Armoury: House'
        data:
          priority: 1
- id: alert_3d_print_completed
  alias: 'Alert: 3D Print Completed'
  trigger:
    - platform: state
      entity_id: binary_sensor.sadi_printing
      from: 'on'
      to: 'off'
  action:
    - service: notify.armoury_pushover
      data:
        message: 3D print job is now complete.
        title: 'The Armoury: House'
        data:
          priority: 0
- id: alert_3d_print_error
  alias: 'Alert: 3D Print Error'
  trigger:
    - platform: state
      entity_id: binary_sensor.sadi_printing_error
      from: 'off'
      to: 'on'
  action:
    - service: notify.armoury_pushover
      data:
        message: An error occurred while a 3D print was being made!
        title: 'The Armoury: House'
        data:
          priority: 1
- id: alert_garage_controller_offline
  alias: 'Alert: Garage Controller Offline'
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_controller
      from: 'on'
      to: 'off'
      for:
        minutes: 30
  action:
    - service: notify.armoury_pushover
      data:
        message: The garage controller is no longer available on the network.
        title: 'The Armoury: Garage Controller'
        data:
          priority: 1
- id: opensprinkler_controller_offline
  alias: 'Alert: OpenSprinkler Offline'
  trigger:
    - platform: state
      entity_id: binary_sensor.opensprinkler_controller
      from: 'on'
      to: 'off'
      for:
        minutes: 30
  action:
    - service: notify.armoury_pushover
      data:
        message: The OpenSprinkler controller is no longer available on the network.
        title: 'The Armoury: OpenSprinkler Controller'
        data:
          priority: 1
- id: alert_hottub_temp_sensor_offline
  alias: 'Alert: Hot Tub Temeprature Service Offline'
  trigger:
    - platform: state
      entity_id: binary_sensor.hottub_temperature_service
      from: 'on'
      to: 'off'
      for:
        minutes: 30
  action:
    - service: notify.armoury_pushover
      data:
        message: The garage controller is no longer available on the network.
        title: 'The Armoury: Garage Controller'
        data:
          priority: 1
- id: alert_vpn_offline
  alias: 'Alert: VPN Server Offline'
  trigger:
    - platform: state
      entity_id: binary_sensor.vpn_server
      from: 'on'
      to: 'off'
      for:
        minutes: 30
  action:
    - service: notify.armoury_pushover
      data:
        message: The VPN server is no longer available on the network.
        title: 'The Armoury: VPN Service'
        data:
          priority: 1
- id: alert_garage_open_too_long
  alias: 'Alert: Garage Open Too Long'
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_main_door
      from: 'off'
      to: 'on'
      for:
        minutes: 30
  action:
    - service: notify.armoury_pushover
      data:
        message: The garage door has been open for too long. Over 30 minutes.
        title: 'The Armoury: Garage Door Security'
        data:
          priority: 1
- id: alarm_away_triggers
  alias: 'Alarm: Triggers When Set to Away'
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.armoury_alarm_system
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      data:
        entity_id: alarm_control_panel.armoury_alarm_system
- id: alarm_home_triggers
  alias: 'Alarm: Triggers When Set to Home'
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.armoury_alarm_system
      state: armed_home
  action:
    - service: alarm_control_panel.alarm_trigger
      data:
        entity_id: alarm_control_panel.armoury_alarm_system
- id: alarm_night_triggers
  alias: 'Alarm: Triggers When Set to Night'
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.armoury_alarm_system
      state: armed_night
  action:
    - service: alarm_control_panel.alarm_trigger
      data:
        entity_id: alarm_control_panel.armoury_alarm_system
- id: alarm_disarm_keypad_used
  alias: 'Alarm: Disarm When Keypad Used'
  trigger:
    - platform: state
      entity_id: sensor.assa_abloy_yale_push_button_deadbolt_yrd210_alarm_type
      to: '19'
    - platform: state
      entity_id: sensor.assa_abloy_yale_push_button_deadbolt_yrd210_alarm_type_2
      to: '19'
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.armoury_alarm_system
- id: alarm_triggered
  alias: 'Alarm: Perform Actions When Triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.armoury_alarm_system
      to: 'triggered'
  action:
    - service: notify.armoury_pushover
      data:
        message: Alarm System Has Been Triggered!
        title: 'The Armoury: Home'
        data:
          priority: 1
- id: react_turn_couch_light_on
  alias: 'React: Turn Couch Light On'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_hswd100_wall_dimmer_2
        scene_id: 1
        scene_data: 3
  action:
    - service: light.turn_on
      data:
        entity_id: light.aeotec_zw099_smart_dimmer_6_level
        brightness: 255
- id: react_turn_couch_light_off
  alias: 'React: Turn Couch Light Off'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_hswd100_wall_dimmer_2
        scene_id: 2
        scene_data: 3
  action:
    - service: light.turn_off
      data:
        entity_id: light.aeotec_zw099_smart_dimmer_6_level
- id: react_turn_chair_light_on
  alias: 'React: Turn Chair Light On'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_hswd100_wall_dimmer_2
        scene_id: 1
        scene_data: 4
  action:
    - service: light.turn_on
      data:
        entity_id: light.chair_lamp
        brightness: 255
- id: react_turn_chair_light_off
  alias: 'React: Turn Chair Light Off'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_hswd100_wall_dimmer_2
        scene_id: 2
        scene_data: 4
  action:
    - service: light.turn_off
      data:
        entity_id: light.chair_lamp
- id: react_turn_basement_light_on
  alias: 'React: Turn Basement Light On'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_hswd100_wall_dimmer
        scene_id: 1
        scene_data: 3
  action:
    - service: light.turn_on
      data:
        entity_id: light.homeseer_hswd100_wall_dimmer_level_3
        brightness: 255
- id: react_turn_basement_light_off
  alias: 'React: Turn Basement Light Off'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_hswd100_wall_dimmer
        scene_id: 2
        scene_data: 3
  action:
    - service: light.turn_off
      data:
        entity_id: light.homeseer_hswd100_wall_dimmer_level_3
- id: react_turn_office_light_on
  alias: 'React: Turn Office Light On'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_hswd100_wall_dimmer_3
        scene_id: 1
        scene_data: 3
  action:
    - service: light.turn_on
      data:
        entity_id: light.homeseer_hswd100_wall_dimmer_level
        brightness: 255
- id: react_turn_office_light_off
  alias: 'React: Turn Office Light Off'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_hswd100_wall_dimmer_3
        scene_id: 2
        scene_data: 3
  action:
    - service: light.turn_off
      data:
        entity_id: light.homeseer_hswd100_wall_dimmer_level
- id: timed_nightly_backup
  alias: 'Timed: Nightly Backup'
  trigger:
    - platform: time
      at: '03:00:00'
  action:
    - service: hassio.addon_stop
      data:
        addon: "core_mariadb"
    - service: hassio.snapshot_full
      data_template:
        name: "{{ now().strftime('%Y%m%d-%H%M') }}-FullBackupNightly"
    - service: hassio.addon_start
      data:
        addon: "core_mariadb"
