homeassistant:
  # Name of the location where Home Assistant is running
  name: Armoury
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: !secret home_units
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  # Customization file
  customize: !include_dir_merge_named armoury/customize/

cloud:
  google_actions:
    filter:
      include_entities: !include armoury/google_assistant_list.yaml
    entity_config: !include armoury/google_assistant_entity_config.yaml

hassio:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: !secret http_hostname
  ssl_certificate: !secret http_ssl_crt
  ssl_key: !secret http_ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - group
      - media_player
      - trigger

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group

# Enabled the recorder and keeps history for 30 days max
recorder:
    purge_keep_days: 30

# Enables a map showing the location of tracked devices
map:

# Enables the sun component
sun:

# Text to speech
tts:
  - platform: google

# Enable MQTT
mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pass

# Enable Pushover
notify:
  - name: armoury_pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# Enable Chromecast
cast:

# Enable Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret 

# Enable Philips Hue
hue:
  bridges:
    - host: !secret philips_hue_ip
      filename: phue.conf

# Enable Octo-print
octoprint:
  host: !secret 3d_printer_controller_ip
  api_key: !secret 3d_printer_controller_api_key
  bed: !secret 3d_printer_controller_heated_bed
  number_of_tools: !secret 3d_printer_controller_tools

# Enable Trackers
device_tracker:
  - platform: owntracks

# Enable OpenWeatherMap
weather:
  - platform: openweathermap
    api_key: !secret open_weather_map_api_key

# Enable Z-Wave
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_secure_key

alarm_control_panel: !include armoury/alarm_control_panel.yaml

group: !include_dir_merge_named armoury/group
binary_sensor: !include_dir_list armoury/binary_sensor
sensor: !include_dir_list armoury/sensor
switch: !include_dir_list armoury/switch
input_number: !include_dir_merge_named armoury/input/number
input_select: !include_dir_merge_named armoury/input/select

shell_command: !include armoury/shell_command.yaml
automation: !include automations.yaml
script: !include scripts.yaml
