security:
  name: Security Sensors
  entities:
    - sensor.front_door_sensor_human_readable
    - sensor.side_door_sensor_human_readable
    - binary_sensor.master_bedroom_multisensor_01_motion_sensor
    - sensor.garage_main_door_human_readable
