- platform: manual
  name: Armoury Alarm System
  code: !secret home_alarm_code
  pending_time: 30
  trigger_time: 15
  armed_home:
    pending_time: 0
  armed_away:
    pending_time: 30
  armed_night:
    pending_time: 0
  triggered:
    pending_time: 20
