- platform: manual
  name: Armoury Alarm System
  code: !secret home_alarm_code
  arming_time: 60
  delay_time: 30
  trigger_time: 15
  armed_home:
    arming_time: 0
    delay_time: 0
  armed_away:
    arming_time: 60
  armed_night:
    arming_time: 0
    delay_time: 0
