light.Aeotec_ZW099_Smart_Dimmer_6_Level:
  name: Couch Lamp
  room: Living Room
#  type: 'action.devices.types.LIGHT'
light.chair_lamp:
  name: Chair Lamp
  room: Living Room
#  type: 'action.devices.types.LIGHT'
light.bedside_left:
  name: Bedside Left
  room: Master Bedroom
#  type: 'action.devices.types.LIGHT'
light.bedside_right:
  name: Bedside Right
  room: Master Bedroom
#  type: 'action.devices.types.LIGHT'
light.homeseer_hswd100_wall_dimmer_level_2:
  name: Doorway Light
  room: Living Room
#  type: 'action.devices.types.LIGHT'
light.homeseer_hswd100_wall_dimmer_level_3:
  name: Basement Lights
  room: Basement
#  type: 'action.devices.types.LIGHT'
light.homeseer_hswd100_wall_dimmer_level:
  name: Office Light
  room: Office
#  type: 'action.devices.types.LIGHT'
light.kitchen_cabinet:
  name: Kitchen Cabinet
  room: Kitchen
#  type: 'action.devices.types.LIGHT'
light.dining_room_1:
  name: Dining Room 1
  room: Dining Room
#  type: 'action.devices.types.LIGHT'
light.dining_room_2:
  name: Dining Room 2
  room: Dining Room
#  type: 'action.devices.types.LIGHT'
light.dining_room_3:
  name: Dining Room 3
  room: Dining Room
#  type: 'action.devices.types.LIGHT'
switch.Aeotec_ZW096_Smart_Switch_6_Switch:
  name: Fireplace
  room: Master Bedroom
#  type: 'action.devices.types.OUTLET'
script.control_garage_door:
  name: Garage Door
  room: Garage
#  type: 'action.devices.types.SCENE'
lock.assa_abloy_yale_push_button_deadbolt_yrd210_locked:
  name: Front Door
  room: Living Room
#  type: 'action.devices.types.LOCK'
lock.assa_abloy_yale_push_button_deadbolt_yrd210_locked_2:
  name: Side Door
  room: Space
#  type: 'action.devices.types.LOCK'
