light.Aeotec_ZW099_Smart_Dimmer_6_Level:
  expose: true
  name: Couch Lamp
light.homeseer_hswd100_wall_dimmer_level_2:
  expose: true
  name: Doorway Light
light.homeseer_hswd100_wall_dimmer_level:
  expose: true
  name: Office Light
switch.Aeotec_ZW096_Smart_Switch_6_Switch:
  expose: true
  name: Fireplace
script.control_garage_door:
  expose: true
  name: Garage Door
script.lock_front_door:
  expose: true
  name: Lock Front
script.unlock_front_door:
  expose: false
  name: Unlock Front
script.lock_side_door:
  expose: true
  name: Lock Side
script.unlock_side_door:
  expose: false
  name: Unlock Side
